# Copyright 2019 - 2021 Alexander Grund
# Copyright 2025 Matt Borland
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
#
# Sample codecov configuration file. Edit as required

codecov:
  max_report_age: off
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: yes

# Enable branch coverage tracking in status checks
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        branches: true    # This enables branch coverage tracking

# Change how pull request comments look
comment:
  layout: "reach,diff,flags,files,footer"
  show_carryforward_flags: true
  branches: true    # This displays branch coverage in comments
