# Copyright 2019 - 2021 Alexander Grund
# Copyright 2025 Matt Borland
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)
#
# Sample codecov configuration file. Edit as required

codecov:
  max_report_age: off
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        # Enable branch coverage tracking
        branches: true
        # Track branch coverage metrics
        flags: null
        paths: null
        # Specify metrics to track
        measurements:
          - branches
          - lines
    patch:
      default:
        # Enable branch coverage for patch status as well
        target: auto
        branches: true
        # Track branch coverage metrics in patches
        measurements:
          - branches
          - lines

# Change how pull request comments look
comment:
  layout: "reach,diff,flags,files,footer"
  show_carryforward_flags: true
  branches: true
  # Show branch coverage metrics in comments
  show_branch: true
  # Show uncovered lines in comments
  show_uncovered: true

# Ignore specific files or folders. Glob patterns are supported.
# See https://docs.codecov.com/docs/ignoring-paths
ignore:
  - test/**
  - test/**/*
  - test/*
