////
Copyright 2025 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#Bit]
= <bit>
:idprefix: bit_

The following are functions analagous to those found in C\++20's https://en.cppreference.com/w/cpp/header/bit[<bit>] header, but for `boost::int128::uint128_t`.
None of these functions applied to signed integral types, and thus none have overloads for `boost::int128::int128_t`.
All of these functions are available using C ++14 like the rest of the library.

[#has_single_bit]
== has_single_bit

Checks if `x` is an integral power of two.
Returns `true` if `x` is a power of two; otherwise `false`

[source,c++]
----
namespace boost {
namespace int128 {

constexpr bool has_single_bit(uint128_t x) noexcept;

} // namespace int128
} // namespace boost
----

[#countl_zero]
== countl_zero

Returns the number of consecutive 0 bits in the value `x`, starting from the most significant.

[source,c++]
----

namespace boost {
namespace int128 {

constexpr int countl_zero(uint128_t x) noexcept;

} // namespace int128
} // namespace boost

----

[#countl_one]
== countl_one

Returns the number of consecutive 1 bits in the value `x`, starting from the most significant.

[source,c++]
----

namespace boost {
namespace int128 {

constexpr int countl_one(uint128_t x) noexcept;

} // namespace int128
} // namespace boost

----

[#bit_width]
== bit_width

If `x` is not zero, returns the number of bits needed to store the value `x`.
If `x` is zero, returns 0

[source,c++]
----

namespace boost {
namespace int128 {

constexpr int bit_width(uint128_t x) noexcept;

} // namespace int128
} // namespace boost

----

[#bit_ceil]
== bit_ceil

Returns the smallest integral power of two that is not smaller than `x`.

[source, c++]
----
namespace boost {
namespace int128 {

constexpr uint128_t bit_ceil(uint128_t x) noexcept;

} // namespace int128
} // namespace boost
----

[#bit_floor]
== bit_floor

Returns the smallest integral power of two that is not greater than `x`.
If `x` is 0 then returns 0.

[source, c++]
----
namespace boost {
namespace int128 {

constexpr uint128_t bit_floor(uint128_t x) noexcept;

} // namespace int128
} // namespace boost
----

[#countr_zero]
== countr_zero

Returns the number of consecutive 0 bits in the value `x`, starting from the least significant.

[source,c++]
----

namespace boost {
namespace int128 {

constexpr int countr_zero(uint128_t x) noexcept;

} // namespace int128
} // namespace boost

----

[#countr_one]
== countr_one

Returns the number of consecutive 1 bits in the value `x`, starting from the least significant.

[source,c++]
----

namespace boost {
namespace int128 {

constexpr int countr_one(uint128_t x) noexcept;

} // namespace int128
} // namespace boost

----

[#rotl]
== rotl

Computes the result of bitwise left-rotating the value of `x` by `s` positions.
This operation is also known as a left circular shift.

[source,c++]
----

namespace boost {
namespace int128 {

constexpr uint128_t rotl(uint128_t x, int s) noexcept;

} // namespace int128
} // namespace boost

----

[#rotr]
== rotr

Computes the result of bitwise right-rotating the value of `x` by `s` positions.
This operation is also known as a right circular shift.

[source,c++]
----

namespace boost {
namespace int128 {

constexpr uint128_t rotr(uint128_t x, int s) noexcept;

} // namespace int128
} // namespace boost

----
