////
Copyright 2024 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#hmac]
:idprefix: hmac_

= HMAC

This library provides a robust implementation of HMAC (Hash-based Message Authentication Code) as specified in https://datatracker.ietf.org/doc/html/rfc2104[RFC 2104].
HMAC is a widely used mechanism for message authentication that combines a cryptographic hash function with a secret key to ensure data integrity and authenticity.

== Overview
HMAC is designed to provide a secure way to verify both the data integrity and the authenticity of a message. It uses a hash function (such as SHA-256, SHA-3/512, etc.) in combination with a secret key to generate a message authentication code (MAC). The MAC can then be used to verify that the message has not been altered and that it comes from an authenticated sender.

== Template Class Implementation
Our HMAC implementation is designed as a template class, allowing it to work seamlessly with any of our hashers. This flexibility means you can choose the most appropriate hashing algorithm for your specific use case without needing to modify the HMAC code itself. Here's how you might instantiate and use the HMAC class:

[source, c++]
----
boost::crypt::hmac<boost::crypt::sha512_hasher> hmac;
const auto state_1 {hmac.init("key", 3)};
BOOST_TEST(state_1 == boost::crypt::state::success);

std::string msg {"The quick brown fox jumps over the lazy dog"};
const auto state_2 {hmac.process_bytes(msg)};
BOOST_TEST(state_2 == boost::crypt::state::success);

hmac.finalize();
const auto res {hmac.get_digest()};
----


== Key Recovery and Reuse
One of the unique features of our HMAC implementation is the ability to recover the inner and outer keys after initialization.
This can be useful in scenarios where you need to compute HMACs for short messages repeatedly, as it allows you to avoid recalculating these keys each time.

Continuing from our above example:
[source, c++]
----
boost::crypt::hmac<boost::crypt::sha512_hasher> hmac;
const auto state_1 {hmac.init(std::string{"key"})};
BOOST_TEST(state_1 == boost::crypt::state::success);

std::string msg {"The quick brown fox jumps over the lazy dog"};
const auto state_2 {hmac.process_bytes(msg)};
BOOST_TEST(state_2 == boost::crypt::state::success);

BOOST_TEST(hmac.finalize() == boost::crypt::state::success);

const auto res {hmac.get_digest()};

const auto outer_key {hmac.get_outer_key()};
const auto inner_key {hmac.get_inner_key()};

// Do some stuff

boost::crypt::hmac<boost::crypt::sha512_hasher> hmac2;

hmac2.init_from_keys(inner_key, outer_key);

std::string msg2 {"The quick brown fox jumps over the lazy dog"};
const auto state_3 {hmac2.process_bytes(msg)};
BOOST_TEST(state_3 == boost::crypt::state::success);

hmac2.finalize();
const auto res2 {hmac2.get_digest()};
----

== Security Considerations
It is crucial to treat the inner and outer keys with the same level of security as the original secret key.
These keys should be stored securely and not exposed to unauthorized parties.
By providing this flexibility and functionality, our HMAC implementation aims to offer a secure, efficient, and versatile solution for message authentication in your applications.

== Reference

[source, c++]
----
namespace boost {
namespace crypt {

BOOST_CRYPT_EXPORT template <typename HasherType>
class hmac
{
public:

    static constexpr boost::crypt::size_t block_size {HasherType::block_size};
    using return_type = typename HasherType::return_type;
    using key_type = compat::array<compat::byte, block_size>;

BOOST_CRYPT_GPU_ENABLED_CONSTEXPR hmac() noexcept = default;

    template <compat::size_t Extent = compat::dynamic_extent>
    explicit BOOST_CRYPT_GPU_ENABLED_CONSTEXPR hmac(const compat::span<const compat::byte, Extent> key) noexcept;

    BOOST_CRYPT_GPU_ENABLED_CONSTEXPR ~hmac() noexcept;

    BOOST_CRYPT_GPU_ENABLED_CONSTEXPR auto init_from_keys(const key_type& inner_key,
                                                          const key_type& outer_key) noexcept -> state;

    template <compat::size_t Extent = compat::dynamic_extent>
    BOOST_CRYPT_GPU_ENABLED_CONSTEXPR auto init(compat::span<const compat::byte, Extent> data) noexcept -> state;

    template <concepts::sized_range SizedRange>
    BOOST_CRYPT_GPU_ENABLED auto init(SizedRange&& data) noexcept -> state;

    template <compat::size_t Extent = compat::dynamic_extent>
    BOOST_CRYPT_GPU_ENABLED_CONSTEXPR auto process_bytes(compat::span<const compat::byte, Extent> data) noexcept -> state;

    template <concepts::sized_range SizedRange>
    BOOST_CRYPT_GPU_ENABLED auto process_bytes(SizedRange&& data) noexcept -> state;

    BOOST_CRYPT_GPU_ENABLED_CONSTEXPR auto finalize() noexcept -> state;

    [[nodiscard]] BOOST_CRYPT_GPU_ENABLED_CONSTEXPR auto get_digest() const noexcept -> compat::expected<return_type, state>;

    template <compat::size_t Extent = compat::dynamic_extent>
    [[nodiscard]] BOOST_CRYPT_GPU_ENABLED_CONSTEXPR
    auto get_digest(compat::span<compat::byte, Extent> data) const noexcept -> state;

    template <concepts::writable_output_range Range>
    [[nodiscard]] BOOST_CRYPT_GPU_ENABLED auto get_digest(Range&& data) const noexcept -> state;

    [[nodiscard]] BOOST_CRYPT_GPU_ENABLED_CONSTEXPR auto get_outer_key() const noexcept -> key_type;

    [[nodiscard]] BOOST_CRYPT_GPU_ENABLED_CONSTEXPR auto get_inner_key() const noexcept -> key_type;

} //namespace crypt
} //namespace boost
----
