////
Copyright 2025 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#overview]
= Overview
:idprefix: overview_

== Description

Boost.Int128 is a portable implementation of a signed, and an unsigned 128-bit integer and related functionality (e.g. bit counting).

The library is header-only, has no dependencies, and requires only C++14.

== Motivation

128-bit integers are remarkably useful in a number of domains, but portability is often an issue.
An example is a 64-bit machine running Linux (say Ubuntu 24.04) has `__int128`, but the same exact machine running Windows does not have this type.

== Use Cases

Anywhere 128-bits are needed.

== Supported Compilers

Boost.Int128 is tested natively on Ubuntu (x86_64, s390x, and aarch64), macOS (x86_64, and Apple Silicon), and Windows (x32 and x64);
as well as emulated PPC64LE and STM32 using QEMU with the following compilers:

* GCC 6 and later
* Clang 5 and later
* Visual Studio 2019 (14.2) and later
* Intel OneAPI DPC++ 2024.2 and later

Tested on https://github.com/cppalliance/int128/actions[Github Actions] and https://drone.cpp.al/cppalliance/int128[Drone].
Coverage can be found on https://app.codecov.io/gh/cppalliance/int128[Codecov].
