////
Copyright 2024 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#overview]
= Overview
:idprefix: overview_

== Description

Boost.Crypt is cryptographic module aiming for FIPS 140-3 certification.
The primary goal of this library is to be the safest implemenation, not the fastest.

WARNING: This library is currently uncertified

The library is header-only, has no dependencies, and requires C++20.

== Motivation

This library will be a ground-up, modern, and memory safe implementation of standard cryptographic routines.
Since it is header only and has no dependencies it is trivial to integrate into any project.
It also offers native CUDA support to massively parallelize these routines (such as hashing thousands of files simultaneously)

== Use Cases

Anywhere where security is needed.

== Supported Compilers

Boost.Crypt is tested natively on Ubuntu (x86_64, s390x, and aarch64), macOS (x86_64, and Apple Silicon), and Windows (x32 and x64);
as well as emulated PPC64LE and STM32 using QEMU with the following compilers:

* GCC 11 and later
* Clang 15 and later
* Visual Studio 2019 (14.2) and later
* Intel OneAPI DPC++ 2024.2 and later
* CUDA Toolkit 12.5 and later (Both NVCC and NVRTC)

Tested on https://github.com/cppalliance/crypt/actions[Github Actions] and https://drone.cpp.al/cppalliance/crypt[Drone].
Coverage can be found on https://app.codecov.io/gh/cppalliance/crypt[Codecov].
