////
Copyright 2024 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#state]
:idprefix: state_

= State

The state `enum class` allows you to verify the validity of the state of an object.
The following are the possible states:

- `success` - The hasher is proceeding without issue
- `null` - A null pointer was passed to hasher
- `input_too_long` - The number of bytes passed to the hasher object has exceeded the range of `size_t`
- `insufficient_entropy` - The input entropy + nonce length is not at least 3/2 security strength
- `out_of_memory` - `ENOMEM` returned by memory allocation
- `requires_reseed` - The number of cycles an object has been used exceeded the design amount
- `uninitialized` - An object has not been initialized properly before use
- `state_error` - A misuse has occurred such as a hasher object was not reinitialized after calling `.get_digest()`. The simple solution is to call `.init()` and try again.

[source, c++]
----

namespace boost::crypt {

enum class state
{
    success,                    // no issues
    null,                       // nullptr as parameter
    input_too_long,             // input data too long (exceeded size_t)
    insufficient_entropy,       // Entropy + Nonce length was not at least 3/2 security strength
    out_of_memory,              // Memory exhaustion reported by a function
    requires_reseed,            // The number of cycles has exceeded the specified amount
    uninitialized,              // Random bits can not be provided since the generator is uninitialized
    requested_too_many_bits,    // 2^19 bits is all that's allowed per request
    state_error                 // added more input after get_digest without re-init
};

} // namespace boost::crypt

----
