////
Copyright 2025 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#Bit]
= `<bit>` Support
:idprefix: bit_

[source,c++]
----
#include <boost/int128/bit.hpp>
----

The following are functions analogous to those found in pass:[C++20] https://en.cppreference.com/w/cpp/header/bit[<bit>] header, but for `boost::int128::uint128`.
None of these functions apply to signed integral types, and thus none have overloads for `boost::int128::int128`.
All of these functions are available using pass:[C++14] like the rest of the library.

[#has_single_bit]
== has_single_bit

Checks if `x` is an integral power of two.
Returns `true` if `x` is a power of two; otherwise `false`

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr bool has_single_bit(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#countl_zero]
== countl_zero

Returns the number of consecutive `0` bits in the value `x`, starting from the most significant.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr int countl_zero(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#countl_one]
== countl_one

Returns the number of consecutive `1` bits in the value `x`, starting from the most significant.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr int countl_one(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#bit_width]
== bit_width

If `x` is not zero, returns the number of bits needed to store the value `x`.
If `x` is zero, returns 0

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr int bit_width(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#bit_ceil]
== bit_ceil

Returns the smallest integral power of two that is not smaller than `x`.

[source, c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr uint128 bit_ceil(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#bit_floor]
== bit_floor

Returns the largest integral power of two that is not greater than `x`.
If `x` is 0 then returns 0.

[source, c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr uint128 bit_floor(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#countr_zero]
== countr_zero

Returns the number of consecutive `0` bits in the value `x`, starting from the least significant.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr int countr_zero(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#countr_one]
== countr_one

Returns the number of consecutive `1` bits in the value `x`, starting from the least significant.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr int countr_one(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#rotl]
== rotl

Computes the result of bitwise left-rotating the value of `x` by `s` positions.
This operation is also known as a left circular shift.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr uint128 rotl(uint128 x, int s) noexcept;

} // namespace int128
} // namespace boost
----

[#rotr]
== rotr

Computes the result of bitwise right-rotating the value of `x` by `s` positions.
This operation is also known as a right circular shift.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr uint128 rotr(uint128 x, int s) noexcept;

} // namespace int128
} // namespace boost
----

[#popcount]
== popcount

Returns the number of `1` bits in `x`.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr int popcount(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

[#byteswap]
== byteswap

Reverses the bytes in the given integer value `x`.

[source,c++]
----
namespace boost {
namespace int128 {

BOOST_INT128_HOST_DEVICE constexpr uint128 byteswap(uint128 x) noexcept;

} // namespace int128
} // namespace boost
----

