////
Copyright 2025 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#Charconv]
= <charconv>
:idprefix: charconv_

The following functions are all overloads injected into https://www.boost.org/doc/libs/master/libs/charconv/doc/html/charconv.html[Boost.Charconv].

IMPORTANT: Unlike the rest of the library, using this header depends on Boost.Charconv being present. This header will `#error` if Boost.Charconv is missing

[#to_chars]
== to_chars

`to_chars` is a set of functions that attempts to convert `value` into a character buffer specified by `[first, last)`.
For full documentation and explanation see the Boost.Charconv https://www.boost.org/doc/libs/master/libs/charconv/doc/html/charconv.html[`to_chars` docs]

[source,c++]
----
#include <boost/int128/charconv.hpp>

namespace boost {
namespace charconv {

BOOST_CHARCONV_CONSTEXPR to_chars(char* first, char* last, int128::uint128_t, int base = 10) noexcept;

BOOST_CHARCONV_CONSTEXPR to_chars(char* first, char* last, int128::int128_t, int base = 10) noexcept;

} // namespace charconv
} // namespace boost
----

NOTE: These functions are in the namespace `boost::charconv`, and not `boost::int128`

[#from_chars]
== from_chars

`from_chars` is a set of functions that parse a string from `[first, last)` in an attempt to convert the string into value according to the chars_format specified (if applicable).
For full documentation and explanation see the Boost.Charconv https://www.boost.org/doc/libs/master/libs/charconv/doc/html/charconv.html[`from_chars` docs]

[source,c++]
----
#include <boost/int128/charconv.hpp>

namespace boost {
namespace charconv {

constexpr from_chars_result from_chars(const char* first, const char* last, int128::uint128_t& value, int base = 10) noexcept;

// Allows both std::string and std::string_view (when available)
constexpr from_chars_result from_chars(core::string_view sv, int128::uint128_t& value, int base = 10) noexcept;

constexpr from_chars_result from_chars(const char* first, const char* last, int128::int128_t& value, int base = 10) noexcept;

// Allows both std::string and std::string_view (when available)
constexpr from_chars_result from_chars(core::string_view sv, int128::int128_t& value, int base = 10) noexcept;

} // namespace charconv
} // namespace boost

----
