////
Copyright 2025 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#configuration]
= Configuration Macros
:idprefix: config_

== User Configurable Macros

[#no_int128]
- `BOOST_INT128_NO_BUILTIN_INT128`: The user may define this when they do not want the internal implementations to rely on builtin `\__int128` or `unsigned __int128` types.

[#sign_compare]
- `BOOST_INT128_ALLOW_SIGN_COMPARE` - Allows only comparisons between this library's types, and built-in types of the opposite sign.

IMPORTANT: DISABLED BY DEFAULT FOR CORRECTNESS

[#sign_conversion]
- `BOOST_INT128_ALLOW_SIGN_CONVERSION` - Allows operations between this library's types, and built-in types of opposite signedness, to include sign comparisons.

IMPORTANT: DISABLED BY DEFAULT FOR CORRECTNESS

== Automatic Configuration Macros

- `BOOST_INT128_HAS_INT128`: This is defined when compiling on a platform that has builtin `\___int128` or `unsigned __int128` types (e.g. `\__x86_64___`).

- `BOOST_INT128_ENDIAN_LITTLE_BYTE`: Defined to `1` if the machine architecture is little endian, otherwise `0`.

- `BOOST_INT128_ENDIAN_BIG_BYTE`: Defined to `1` if the machine architecture is big endian, otherwise `0`.
